name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug file structure
        run: ls -R

      - name: Copy source files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "public,src,package.json,package-lock.json,next.config.ts,tsconfig.json,postcss.config.js"
          target: /www/wwwroot/frontend-user

      - name: install & restart
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /www/wwwroot/frontend-user
            npm install --production
            npm run build
            pm2 stop frontend-user || true
            pm2 delete frontend-user || true
            pm2 start npm --name "frontend-user" -- run start
            pm2 save
